title: "Lion Behrens"
description: M.Sc. student of Methodology and Statistics. <bf>Political Behavior - Stats - Methods</bf>
email: l.behrens@uu.nl
twitter_username: LionBehrens
github_username: Lion-Be
rss: false

curriculum: 
  url: /cv.pdf
  
nav_ext_links:
  - name: CV
    url: https://lion-be.github.io/cv.pdf

remote_theme: academic
