title: "Lion Behrens"
description: Political Behavior. Statistics. Methods.  
email: l.behrens@uu.nl
twitter_username: LionBehrens
github_username: Lion-Be

pitch: Political Behavior. Statistics. Methods. 

curriculum: 
  url: /cv.pdf

remote_theme: academic
