title: "Lion Behrens"
description: Political Behavior. Statistics. Methods.  
email: l.behrens@uu.nl
twitter_username: LionBehrens
github_username: Lion-Be

curriculum: 
  url: /cv.pdf
  
nav_ext_links:
  - name: CV
    url: https://github.com/Lion-Be/Lion-Be.github.io/blob/master/cv.pdf

remote_theme: academic
